## Vector
- 벡터는 스칼라의 집합으로 뒤이어 배울 행렬을 구성하는 기본 단위로, 스칼라가 크기(magnitude)만 나타낸다면 벡터는 크기와 방향(direction)까지 동시에 나타낸다.
- 일반적으로 벡터를 표현할 때에는 Column vector 형태를 기본으로 사용.

## Vector 연산 성질
u, v, w는 벡터, a, b는 스칼라
1. $u + v = v + u$ (commutative law. 벡터 덧셈은 교환법칙이 성립한다.)
2. $(u + v) + w = u + (v + w)$ (associative law. 벡터 덧셈은 결합법칙이 성립한다.)
3. $u + 0 = 0 + u$ (벡터 뎃셈은 항등원이 존재하며 그 항등원은 영벡터다.)
4. $u + (-u) = 0$ (벡터 덧셈에 대한 역원은 해당 벡터의 역수.)
5. $a(bu) = (ab)u$ (스칼라곱에 대한 결합법칙이 성립.)
6. $a(u + v) = au + av$ (스칼라 곱과 벡터 덧셈에 대해 분배 법칙이 성립한다.)
7. $(a + b)u = au + bu$

벡터 연산의 성질은 Linearity의 조건을 만족함을 뜻한다.
Linearity는 아래 두 조건을 만족할 때 성립하는 특성.
- Additivity : f(x + y) = f(x) + f(y)
- Homogeneity : f(cx) = cf(x)

벡터 덧셈은 교환법칙, 결합법칙 그리고 항등원, 역원이 성립함에 따라 Additivity가 충족된다. 그리고 6번 스칼라 곱과 벡터의 덧셈이 성립함에 따라 Homogenity가 충족.

In [1]:
import numpy as np

벡터의 덧셈, 뺄셈, 원소(element-wise) 곱 그리고 원소 나눗셈은 피연산자 벡터간 차원이 동일 할 때 가능한 연산들이다.

In [2]:
## Vector Addition
## Python
u = [1, 2, 3]
v = [4, 5, 6]

if len(u) == len(v): ## 두 벡터의 차원이 같을 때 벡터 덧셈 연산이 가능하다.
    result = []
    for idx in range(len(u)):
        result.append(u[idx] + v[idx])
    print(result)

## Numpy
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print(u + v)

[5, 7, 9]
[5 7 9]


In [3]:
## Vector Subtraction
## Python
u = [7, 3, 9]
v = [2, 5, 7]

if len(u) == len(v):
    result = []
    for idx in range(len(u)):
        result.append(u[idx] - v[idx])
    print(result)

## Numpy
u = np.array([7, 3, 9])
v = np.array([2, 5, 7])
print(u - v)

[5, -2, 2]
[ 5 -2  2]


In [4]:
## Scalar Multiplication
## Python
c = 3
u = [2, 4, 3]

for idx in range(len(u)):
    u[idx] *= c
print(u)

## Numpy
c = 3
u = np.array([2, 4, 3])
print(c * u)

[6, 12, 9]
[ 6 12  9]


In [5]:
## Element-wise multiplication
## Python
u = [1, 2, 4]
v = [7, 3, 2]

if len(u) == len(v):
    result = []
    for idx in range(len(u)):
        result.append(u[idx] * v[idx])
    print(result)

## Numpy
u = np.array([1, 2, 4])
v = np.array([7, 3, 2])
print(u * v)

[7, 6, 8]
[7 6 8]


In [6]:
## Element-wise Division
## Python
u = [6, 5, 9]
v = [2, 2, -3]

if len(u) == len(v):
    result = []
    for idx in range(len(u)):
        result.append(u[idx] / v[idx])
    print(result)

## Numpy
u = np.array([6, 5, 9])
v = np.array([2, 2, -3])
print(u / v)

[3.0, 2.5, -3.0]
[ 3.   2.5 -3. ]


## Matrix
- 행렬은 n개의 스칼라 값을 사각형(Rectangular or Square) 형태로 나열한 것 또는 벡터들의 집합으로 볼 수 있다.  
- row(행)와 column(열)로 indexing이 가능하며, 행렬의 원소들을 entry라고 표현한다.(벡터의 원소는 component.)
- 데이터들의 집합(dataset 혹은 data table)을 행렬로 나타낼 수 있다. 이 때 각 row를 data record(또는 data sample) 각 column을 feature라고 부른다.
- data table을 구성하는 속성값(나이, 성별, 몸무게 또는 국어, 영어, 수학 성적 등)는 Attribute.

## Matrix 연산 성질
1. $A + B = B + A$ 행렬의 덧셈연산에는 교환법칙이 성립한다.
2. $A + (B + C) = (A + B) + C$ 행렬의 덧셈연산은 결합법칙이 성립한다.
3. $A(BC) = (AB)C$ 행렬의 곱셈(matrix multiplication)연산은 결합법칙이 성립한다.
4. $A(B + C) = AB + AC$ left-distribution
5. $(B + C)A = BA + CA$ right-distribution
6. $a(B + C) = aB + aC$ 행렬의 덧셈은 상수배의 분배법칙이 성립한다.
7. $a(bC) = abC$

행렬의 연산 성질도 벡터의 연산 성질과 마찬가지로 Linearity가 성립함으로 이어진다.

벡터의 덧셈, 뺄셈과 마찬가지로 행렬의 덧셈, 뺄셈도 두 행렬의 차원이 같을 때 성립하는 연산이다.

In [7]:
## Matrix Addition
## Python
A = [[2, 7],
     [3, 4], 
     [6, 1]] ## 2 by 3 Rectangular matrix.

B = [[1, 4],
     [4, -1],
     [2, 5]] ## 2 by 3 Rectangular matrix.

if len(A) == len(B) and len(A[0]) == len(B[0]):
    result = []
    for i in range(len(A)): ## Row iter
        row = []
        for j in range(len(A[0])): ## Column iter
            row.append(A[i][j] + B[i][j])
        result.append(row)
    
    print(result)

## Numpy
A = np.array([[2, 7],
              [3, 4],
              [6, 1]])
B = np.array([[1, 4,],
              [4, -1],
              [2, 5]])
print(A+B)

[[3, 11], [7, 3], [8, 6]]
[[ 3 11]
 [ 7  3]
 [ 8  6]]


In [10]:
## Matrix Subtraction
## Python
A = [[2, 7],
     [3, 4],
     [6, 1]]
B = [[1, 4],
     [4, -1],
     [2, 5]]

if len(A) == len(B) and len(A[0]) == len(B[0]):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] - B[i][j])
        result.append(row)
    
    print(result)

## Numpy
A = np.array([[2, 7],
              [3, 4],
              [6, 1]])

B = np.array([[1, 4],
              [4, -1],
              [2, 5]])
print(A - B)

[[1, 3], [-1, 5], [4, -4]]
[[ 1  3]
 [-1  5]
 [ 4 -4]]


In [13]:
## Matrix scalar mutliplication
## Python
A = [[2, 7],
     [3, 4],
     [6, 1]]
c = 2

result = []
for i in range(len(A)):
    row = []
    for j in range(len(A[0])):
        row.append(A[i][j] * c)
    result.append(row)

print(result)

## Numpy
A = np.array([[2, 7],
              [3, 4],
              [6, 1]])
c = 2

print(A * c)


[[4, 14], [6, 8], [12, 2]]
[[ 4 14]
 [ 6  8]
 [12  2]]


In [15]:
## Element-wise matrix multiplication
## Python
A = [[1, 5], [6, 4], [2, 7]]
B = [[5, -1], [1, 2], [4, 1]]

if len(A) == len(B) and len(A[0]) == len(B[0]):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] * B[i][j])
        result.append(row)
print(result)

## Numpy
A = np.array([[1, 5], [6, 4], [2, 7]])
B = np.array([[5, -1], [1, 2], [4, 1]])
print(A * B)

[[5, -5], [6, 8], [8, 7]]
[[ 5 -5]
 [ 6  8]
 [ 8  7]]


In [29]:
## Matrix Multiplication
## Python
A = [[2, 7], [3, 4], [5, 2]]
B = [[3, -3, 5], [-1, 2, -1]]

## rows of A times columns of B
if len(A[0]) == len(B):
    result = []
    for i in range(len(A)): ## A의 row1과 B의 col1, col2, col3이 각각 result의 row1을 채운다. 간단하게 보면 A의 row 수 만큼 반복.
        row = []
        for j in range(len(B[0])): ## B의 column 수 만큼 반복.
            entry = 0
            for k in range(len(B)): ## A의 columns 또는 B의 rows
                entry += (A[i][k] * B[k][j])
            row.append(entry)
        result.append(row)
print(result)

## Numpy
A = np.array([[2, 7], [3, 4], [5, 2]])
B = np.array([[3, -3, 5], [-1, 2, -1]])
print(np.matmul(A, B))

[[-1, 8, 3], [5, -1, 11], [13, -11, 23]]
[[ -1   8   3]
 [  5  -1  11]
 [ 13 -11  23]]
