## 전치행렬(Transposed Matrix)
- 기존 행렬의 행과 열을 바꾼 행렬.
- 따라서 기존 행렬의 행 번호가 열 번호가 되고 열 번호가 행 번호가 된다.
- 이로 인해 원래의 행렬을 전치(transpose)하게 되면 행렬의 크기도 바뀌게 된다.
- 행렬 A가 transpose 되었음을 A의 오른쪽위에 T를 붙여 $A^T$로 나타낸다.

## 전치행렬의 성질
1. $(A^T)^T=A$
2. $(A+B)^T = A^T+B^T$
3. $(A-B)^T = A^T-B^T$
4. $(aA)^T = aA^T$
5. $(AB)^T = B^TA^T$

1번 ~ 4번 특성은 사실 당연하게 볼 수 있다. 단, 5번 특성의 경우 matrix multiplication의 순서가 역순(reverse order)이 되는 점을 기억해야한다.

In [7]:
import numpy as np

In [8]:
## Matrix Transpose
## Python 
A = [[1, 5], 
     [3, 4], 
     [6, 2]] ## 3 by 2 행렬이니까 전치행렬은 2 by 3가 되어야 한다.

## row1 -> column1 row2 -> column2
result = []
for i in range(len(A[0])):
    row = []
    for j in range(len(A)):
        row.append(A[j][i])
    result.append(row)
print(result)

## Numpy
A = np.array([[1, 5], [3, 4], [6, 2]])
AT = np.transpose(A)
print(AT)
    

[[1, 3, 6], [5, 4, 2]]
[[1 3 6]
 [5 4 2]]


## 대칭행렬(Symmetric Matrix)
- 대각원소(diagonal entries)들을 기준으로 좌우가 대칭인 정사각행렬(Square matrix)
- 따라서 원래의 행렬을 transpose 하더라도 그 결과가 원래의 행렬과 동일하다. $A^T=A$

## 대칭행렬의 성질
1. 두 개의 symmetric matrix A, B간 덧셈 또는 뺄셈의 결과 행렬 역시 Symmetric matrix이다.
2. A와 B간 행렬곱(matrix multiplication)의 결과는 symmetic matrix가 아니다.
3. $A^2$ 과 같이 대칭행렬을 n제곱한 결과행렬은 symmetric matrix이다.
4. A가 대칭행렬이 아닐 때, $A^T$와의 행렬곱 결과는 symmetric matrix이다.

특징 4번은 선형대수에서 매우 중요한 특성 중 하나이다. 다시 한 번 적어보자면 행렬 A는 non-symmetirc matrix이다.  
이 때 A의 transpose인 $A^T$와의 곱셈 $A^TA$ 또는 $AA^T$의 결과는 symmetric matrix이다.  
단, 주의할 점은 $AA^T$와 $A^TA$는 같을 수도 있고 다를 수도 있다.

In [23]:
## Symmetric Matrix
## Python
A1 = [[1, 0, 2],
      [0, 2, 1],
      [2, 1, 1]]

A2 = [[1, 5], 
      [3, 4], 
      [6, 2]]

def matrix_transpose(m):
    result = []
    for i in range(len(m[0])):
        row = []
        for j in range(len(m)):
            row.append(m[j][i])
        result.append(row)
    
    return result

def check_symmetric(m, mt):
    if isinstance(m, list):
        if m == mt:
            return True
        else:
            return False
    elif isinstance(m, np.ndarray):
        return np.array_equal(m, mt)

print("===== Python =====")
A1_T = matrix_transpose(A1)
print(A1_T, check_symmetric(A1, A1_T))

A2_T = matrix_transpose(A2)
print(A2_T, check_symmetric(A2, A2_T))

## Numpy
print("===== Numpy =====")
A1 = np.array(A1)
A1_T = A1.transpose()
print(A1_T, check_symmetric(A1, A1_T))

A2 = np.array(A2)
A2_T = A2.transpose()
print(A2_T, check_symmetric(A2, A2_T))


===== Python =====
[[1, 0, 2], [0, 2, 1], [2, 1, 1]] True
[[1, 3, 6], [5, 4, 2]] False
===== Numpy =====
[[1 0 2]
 [0 2 1]
 [2 1 1]] True
[[1 3 6]
 [5 4 2]] False


In [31]:
## Symmetic matrix A의 n제곱은 Symmetic matrix이다.
def matrix_multiplication(A, B):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A)):
            entry = 0
            for k in range(len(A[0])):
                entry += A[i][k] * B[k][j]
            row.append(entry)
        result.append(row)

    return result

A = [[1, 0, 2],
     [0, 2, 1],
     [2, 1, 1]]

AA = A
for i in range(0, 9):
    AA = matrix_multiplication(AA, A)
    print(f"A의 {i+2}제곱은 {AA}, {check_symmetric(AA, matrix_transpose(AA))}")

A의 2제곱은 [[5, 2, 4], [2, 5, 3], [4, 3, 6]], True
A의 3제곱은 [[13, 8, 16], [8, 13, 12], [16, 12, 17]], True
A의 4제곱은 [[45, 32, 50], [32, 38, 41], [50, 41, 61]], True
A의 5제곱은 [[145, 114, 172], [114, 117, 143], [172, 143, 202]], True
A의 6제곱은 [[489, 400, 576], [400, 377, 488], [576, 488, 689]], True
A의 7제곱은 [[1641, 1376, 1954], [1376, 1242, 1665], [1954, 1665, 2329]], True
A의 8제곱은 [[5549, 4706, 6612], [4706, 4149, 5659], [6612, 5659, 7902]], True
A의 9제곱은 [[18773, 16024, 22416], [16024, 13957, 19220], [22416, 19220, 26785]], True
A의 10제곱은 [[63605, 54464, 75986], [54464, 47134, 65225], [75986, 65225, 90837]], True


## 대각행렬(Diagonal Matrix)
- 대각 원소(diagonal entry)들을 제외한 나머지 원소들(off-diagonal entries)이 0인 행렬.
- 따라서 행 번호와 열 번호가 같을 때의 원소는 0이 아니고 다를 때의 원소는 0이다.
- Diagonal matrix의 역행렬은 대각 원소들의 역수들이 주대각선에 배치된 행렬이다.
- 대각 행렬의 거듭제곱은 대각 원소들을 거듭제곱한 행렬.

In [39]:
## 대각행렬이 아닌 행렬 A와 대각 행렬 D의 행렬 곱.
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
D = [[2, 0, 0], [0, 1, 0], [0, 0, 1]]

AD = []
for i in range(len(A)):
    row = []
    for j in range(len(A[0])):
        entry = 0
        for k in range(len(D)):
            entry += A[i][k] * D[k][j]
        row.append(entry)
    AD.append(row)

AD = np.array(AD)
print(f"{AD}") ## 행렬 A의 column1이 D의 첫번째 diagonal entry만큼 값이 커진다. 즉, diagonal matrix가 오른쪽에 곱해지면 scaling matrix가 되는셈.
## column picture로 보면 이해가 매우 쉽다. 행렬 A의 row * D의 column.

DA = np.array(matrix_multiplication(D, A))
print(f"{DA}")
## row picture. 행렬 D의 column * A의 row

[[ 2  2  3]
 [ 8  5  6]
 [14  8  9]]
[[2 4 6]
 [4 5 6]
 [7 8 9]]


In [44]:
## 임의의 행렬 A에서 diagonal matrix를 구한다.
## Python
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

result = []
for i in range(len(A)):
    row = []
    for j in range(len(A[0])):
        if i == j:
            row.append(A[i][j])
        else:
            row.append(0)
    result.append(row)
print(result)

## Numpy
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A_diag = np.diag(np.diag(A))
print(A_diag)

[[1, 0, 0], [0, 5, 0], [0, 0, 9]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


## Identity Matrix
- 대각원소가 1이고 나머지 원소들은 0인 행렬.
- 행렬곱에 대한 항등원 역할을 하는 것이 바로 identity matrix(단위행렬 또는 항등행렬이다.)
- $AI=IA=A$

In [45]:
## n by n identity matrix를 만든다.

def make_identity(n):
    identity_matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        identity_matrix.append(row)
    
    return identity_matrix

make_identity(5)

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [49]:
## Identity matrix와의 행렬곱은 변화가 없다. 행렬곱에 대한 항등원.
## Python
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
I = make_identity(3)

AI = matrix_multiplication(A, I)
print(AI)

IA = matrix_multiplication(I, A)
print(IA)

## Numpy
I = np.identity(3)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

AI = np.matmul(A, I)
IA = I @ A
print(AI)
print(IA)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
